### ISSUE TITLE
64 Bit Binary

### ISSUE THREAD

**Issue by debasishm89** [siberas/IDA2Sym#1]
Is there any way we can have the 64bit compiled binary so that it can be used with 64bit Windbg.

**Comment by siberas** [comment]
hi @debasishm89 , sorry for this late response. I didn't look for new notifications.
At the moment we don't work that much on IDA2Sym. If we have any updates we will publish them of course.

**Comment by debasishm89** [comment]
Thanks for reply. I've made a workaround.
